import type { ComponentEntry } from "./types";

export const canvas: ComponentEntry[] = [
  {
    slug: "magnify",
    name: "放大鏡透鏡",
    nameEn: "Magnify",
    category: "canvas",
    description:
      "跟著游標移動的 WebGL 放大鏡，附 HUD 十字準星、刻度與座標讀數，點擊會激起漣漪。在支援 HTML-in-canvas 的瀏覽器可放大實際內容，其他瀏覽器優雅退回顯示原始內容。",
    dependencies: [],
    props: [
      { name: "size", type: "number", defaultValue: "140", description: "鏡片半徑（CSS 像素）" },
      { name: "zoom", type: "number", defaultValue: "1.5", description: "鏡片內的放大倍率（1–4）" },
      { name: "color", type: "[number, number, number]", defaultValue: "[0.8, 0.8, 0.8]", description: "HUD 主色（RGB，0–1）" },
      { name: "follow", type: "number", defaultValue: "0.25", description: "鏡片跟隨游標的速度（0–1，1 為即時貼齊）" },
      { name: "hud", type: "number", defaultValue: "0.8", description: "HUD 整體強度（0 隱藏所有準星元素）" },
      { name: "aberration", type: "number", defaultValue: "0.8", description: "鏡片內色差強度（0–3）" },
      { name: "haze", type: "number", defaultValue: "0.2", description: "鏡片內的朦朧感（0–1）" },
      { name: "ripples", type: "boolean", defaultValue: "true", description: "點擊時是否激起漣漪" },
      { name: "scrollZoom", type: "boolean", defaultValue: "false", description: "按住 zoomModifier 時允許滾輪調整倍率" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/magnify",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "decrypt-reveal",
    name: "解密顯現",
    nameEn: "Decrypt Reveal",
    category: "canvas",
    description:
      "內容化為不斷跳動的密文字元，游標掃過的範圍即時「解密」還原成真實 UI，解密邊緣帶有閃爍與色差。在支援 HTML-in-canvas 的瀏覽器呈現完整效果，其他瀏覽器優雅退回顯示原始內容。",
    dependencies: [],
    props: [
      { name: "radius", type: "number", defaultValue: "400", description: "游標周圍的解密半徑（CSS 像素）" },
      { name: "softness", type: "number", defaultValue: "0.5", description: "解密邊緣的羽化程度（0–1）" },
      { name: "cell", type: "number", defaultValue: "10", description: "密文字元格高度（CSS 像素，4–40）" },
      { name: "charset", type: "string", defaultValue: "可列印 ASCII", description: "密文使用的字元集" },
      { name: "color", type: "string", defaultValue: '"#4ade80"', description: "密文顏色（任何 CSS 顏色）" },
      { name: "colored", type: "number", defaultValue: "1", description: "字元保留底下 UI 顏色的程度（0 為單色）" },
      { name: "scramble", type: "number", defaultValue: "0.1", description: "持續跳動的密文比例（0–1）" },
      { name: "scrambleSpeed", type: "number", defaultValue: "6", description: "每秒密文變化次數（0–30）" },
      { name: "edgeGlow", type: "number", defaultValue: "2", description: "解密波前的亮度增幅（0–3）" },
      { name: "passthrough", type: "number", defaultValue: "0.15", description: "密文底下透出真實 UI 的程度（0–1）" },
      { name: "background", type: "string", defaultValue: '"#000000"', description: "內容背後的底色，用來區分 UI 與空白" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/decrypt-reveal",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "particle-reveal",
    name: "粒子顯現",
    nameEn: "Particle Reveal",
    category: "canvas",
    description:
      "內容分解成飄散的粒子塵埃，游標移入的範圍才凝聚回清晰畫面，邊緣帶有彎折與色差。在支援 HTML-in-canvas 的瀏覽器呈現完整效果，其他瀏覽器優雅退回顯示原始內容。",
    dependencies: [],
    props: [
      { name: "radius", type: "number", defaultValue: "500", description: "游標周圍的顯現半徑（CSS 像素）" },
      { name: "softness", type: "number", defaultValue: "0.75", description: "顯現邊緣的羽化程度（0–1）" },
      { name: "size", type: "number", defaultValue: "1", description: "粒子顆粒大小（CSS 像素）" },
      { name: "scatter", type: "number", defaultValue: "25", description: "粒子飄離原位的最大距離（CSS 像素）" },
      { name: "drift", type: "number", defaultValue: "1", description: "閒置粒子的漂移速度（0 靜止）" },
      { name: "aberration", type: "number", defaultValue: "40", description: "顯現邊緣的色差強度（CSS 像素）" },
      { name: "bend", type: "number", defaultValue: "50", description: "未顯現內容在邊緣的扭曲程度（CSS 像素）" },
      { name: "background", type: "string", defaultValue: '"#000000"', description: "內容背後的底色，用來區分 UI 與空白" },
      { name: "smoothing", type: "number", defaultValue: "0.25", description: "顯現圈追上游標所需秒數，越高越滯重" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/particle-reveal",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "frost",
    name: "結霜效果",
    nameEn: "Frost",
    category: "canvas",
    description:
      "在內容表面覆上一層會折射光線的冰霜，載入時從邊緣蔓延成形，游標劃過會融出透明痕跡並緩慢重新結凍。在支援 HTML-in-canvas 的瀏覽器會霜化實際內容，其他瀏覽器退回顯示霜面覆蓋層。",
    dependencies: [],
    props: [
      { name: "strength", type: "number", defaultValue: "0.7", description: "霜紋覆蓋強度，越高結凍面積越大" },
      { name: "haze", type: "number", defaultValue: "0.5", description: "整體模糊霧感（0–1）" },
      { name: "refraction", type: "number", defaultValue: "1", description: "冰面折射光線的程度（0 關閉）" },
      { name: "ior", type: "number", defaultValue: "1.31", description: "冰的折射率（水冰約 1.31）" },
      { name: "meltRadius", type: "number", defaultValue: "0.25", description: "游標融冰範圍（0–1，相對高度）" },
      { name: "meltStrength", type: "number", defaultValue: "0.75", description: "懸停融冰的速度（0–1）" },
      { name: "refreeze", type: "number", defaultValue: "2", description: "融化區域重新結凍的速度（0 永不結凍）" },
      { name: "introDuration", type: "number", defaultValue: "2.5", description: "載入時霜從邊緣長出的秒數（0 關閉）" },
      { name: "opacity", type: "number", defaultValue: "0.6", description: "霜層整體不透明度（0–1）" },
      { name: "shimmer", type: "number", defaultValue: "0", description: "霜面亮點的閃爍動畫（0 為靜態）" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/frost",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "liquid",
    name: "液體模擬",
    nameEn: "Liquid",
    category: "canvas",
    description:
      "游標拂過時以 WebGL 流體模擬在 HTML 內容上掀起波紋與色彩拖尾，內容保持可讀、可互動。在支援 HTML-in-canvas 的瀏覽器會扭曲實際內容，其他瀏覽器退回純 HTML 加流體光暈。",
    dependencies: [],
    props: [
      { name: "color", type: "[number, number, number]", defaultValue: "[0.145, 0.239, 0.867]", description: "拖尾顏色（RGB，0–1 範圍）；rainbow 開啟時忽略" },
      { name: "rainbow", type: "boolean", defaultValue: "false", description: "依流動方向著色，取代固定顏色" },
      { name: "radius", type: "number", defaultValue: "0.3", description: "游標攪動的水花半徑" },
      { name: "force", type: "number", defaultValue: "1.1", description: "游標移動施加的力道倍率" },
      { name: "intensity", type: "number", defaultValue: "2", description: "流體色彩殘留的強度" },
      { name: "distortion", type: "number", defaultValue: "0.4", description: "流體扭曲內容的程度" },
      { name: "blend", type: "number", defaultValue: "5", description: "流體顏色覆蓋在內容上的混合量" },
      { name: "densityDissipation", type: "number", defaultValue: "0.96", description: "拖尾每幀保留的比例（越接近 1 越持久）" },
      { name: "velocityDissipation", type: "number", defaultValue: "1", description: "動能每幀保留的比例（越接近 1 越持久）" },
      { name: "curl", type: "number", defaultValue: "1.9", description: "回饋進流場的旋轉力（漩渦感）" },
      { name: "simResolution", type: "number", defaultValue: "128", description: "流體運算網格解析度（初始化後不可變更）" },
      { name: "dyeResolution", type: "number", defaultValue: "512", description: "拖尾貼圖解析度（初始化後不可變更）" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/liquid",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "glass",
    name: "玻璃折射",
    nameEn: "Glass",
    category: "canvas",
    description:
      "一枚跟著游標移動的玻璃鏡片，即時折射並可放大底下的 HTML 內容，含色散與菲涅耳反射。在支援 HTML-in-canvas 的瀏覽器會折射實際內容，其他瀏覽器只顯示鏡片光暈。",
    dependencies: [],
    props: [
      { name: "shape", type: '"circle" | "square" | "rectangle"', defaultValue: '"circle"', description: "鏡片形狀" },
      { name: "size", type: "number", defaultValue: "120", description: "鏡片尺寸（半徑或半高，CSS 像素）" },
      { name: "aspect", type: "number", defaultValue: "1.7", description: "rectangle 形狀的寬高比（1–3）" },
      { name: "corner", type: "number", defaultValue: "32", description: "square 與 rectangle 的圓角（CSS 像素）" },
      { name: "ior", type: "number", defaultValue: "1.5", description: "玻璃折射率（1–2），越高折射越強" },
      { name: "edge", type: "number", defaultValue: "0.7", description: "鏡片中央保持平坦的比例（0–1）" },
      { name: "bevel", type: "number", defaultValue: "4", description: "鏡緣彎折的銳利度（1–10）" },
      { name: "depth", type: "number", defaultValue: "250", description: "光學深度：玻璃懸浮在頁面上方的距離（CSS 像素）" },
      { name: "aberration", type: "number", defaultValue: "1", description: "鏡緣色散強度（0–3），0 停用" },
      { name: "blur", type: "number", defaultValue: "0", description: "磨砂模糊程度（0 為全透明，最大 4）" },
      { name: "reflection", type: "number", defaultValue: "1", description: "鏡緣菲涅耳反射強度（0–2），0 停用" },
      { name: "shine", type: "number", defaultValue: "0.01", description: "鏡緣高光強度（0–2），讓鏡片在素色背景上也看得見" },
      { name: "zoom", type: "number", defaultValue: "1.5", description: "懸停在目標元素上時的放大倍率（1–3）" },
      { name: "targets", type: "string", defaultValue: '"[data-glass-target]"', description: "觸發放大的元素 CSS 選擇器" },
      { name: "follow", type: "number", defaultValue: "0.2", description: "鏡片跟隨游標的速度（0–1），1 為即時貼齊" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/glass",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "glitch",
    name: "故障藝術",
    nameEn: "Glitch",
    category: "canvas",
    description:
      "對 HTML 內容週期性施加水平撕裂、RGB 分離、方塊損毀與掃描雜訊的故障效果，爆發之間內容保持完整可讀。在支援 HTML-in-canvas 的瀏覽器會撕裂實際內容，其他瀏覽器退回純 HTML。",
    dependencies: [],
    props: [
      { name: "intensity", type: "number", defaultValue: "1", description: "整體故障強度（0–2）" },
      { name: "interval", type: "number", defaultValue: "3", description: "爆發間隔秒數；0 表示持續故障" },
      { name: "duration", type: "number", defaultValue: "0.4", description: "每次爆發持續秒數" },
      { name: "slices", type: "number", defaultValue: "24", description: "水平撕裂切片數，越低越大塊" },
      { name: "shift", type: "number", defaultValue: "30", description: "撕裂切片的水平位移量（CSS 像素）" },
      { name: "rgbShift", type: "number", defaultValue: "4", description: "爆發時的 RGB 色版分離量（CSS 像素）" },
      { name: "blocks", type: "number", defaultValue: "0.5", description: "爆發時方塊損毀的數量（0–1）" },
      { name: "noise", type: "number", defaultValue: "0.35", description: "爆發時的類比雜訊與掃描線閃爍（0–1）" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/glitch",
      license: "MIT + Commons Clause",
    },
  },
  {
    slug: "vhs",
    name: "VHS 效果",
    nameEn: "VHS",
    category: "canvas",
    description:
      "把 HTML 內容渲染成老式錄影帶畫面：磁帶波動、逐行抖動、掃描線、雜訊顆粒、色彩溢散與底部磁頭切換雜訊。在支援 HTML-in-canvas 的瀏覽器會處理實際內容，其他瀏覽器退回純 HTML。",
    dependencies: [],
    props: [
      { name: "speed", type: "number", defaultValue: "0.5", description: "磁帶瑕疵的播放速度，1 為正常速度" },
      { name: "wave", type: "number", defaultValue: "1", description: "緩慢水平波動的強度（0–3）" },
      { name: "jitter", type: "number", defaultValue: "0.25", description: "逐行細微水平抖動的強度（0–3）" },
      { name: "crease", type: "number", defaultValue: "0.1", description: "移動中磁帶摺痕帶的強度（0–3）" },
      { name: "switching", type: "number", defaultValue: "0.05", description: "底部磁頭切換雜訊的強度（0–3）" },
      { name: "switchingHeight", type: "number", defaultValue: "0.02", description: "磁頭切換帶高度（畫面比例）" },
      { name: "bloom", type: "number", defaultValue: "0.4", description: "水平光暈溢散強度（0–1）" },
      { name: "aberration", type: "number", defaultValue: "2", description: "RGB 色版錯位量（CSS 像素）" },
      { name: "acBeat", type: "number", defaultValue: "1", description: "沿畫面滾動的亮度節拍（0–1）" },
      { name: "grain", type: "number", defaultValue: "0.1", description: "動態雜訊顆粒的量（0–1）" },
      { name: "scanlines", type: "number", defaultValue: "0.1", description: "CRT 掃描線覆蓋強度（0–1）" },
      { name: "vignette", type: "number", defaultValue: "0", description: "畫面四角變暗的程度（0–1）" },
      { name: "barrel", type: "number", defaultValue: "0", description: "映像管曲面向內彎折的程度（0–1），0 停用" },
      { name: "saturation", type: "number", defaultValue: "1", description: "色彩飽和度，0 為灰階" },
      { name: "exposure", type: "number", defaultValue: "1", description: "最後套用的亮度倍率" },
      { name: "className", type: "string", description: "疊加在外層容器的 class" },
    ],
    source: {
      label: "CanvasUI",
      url: "https://canvasui.dev/docs/components/vhs",
      license: "MIT + Commons Clause",
    },
  },
];
